/********************************************************************************
** Form generated from reading UI file 'syszuxpinyin.ui'
**
** Created by: Qt User Interface Compiler version 5.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SYSZUXPINYIN_H
#define UI_SYSZUXPINYIN_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_Dialog
{
public:
    QHBoxLayout *horizontalLayout;
    QFrame *frame;
    QPushButton *pushButton_n0;
    QPushButton *pushButton_k;
    QPushButton *pushButton_hanzi_right;
    QPushButton *pushButton_n8;
    QPushButton *pushButton_is_hanzi;
    QPushButton *pushButton_d;
    QPushButton *pushButton_up;
    QPushButton *pushButton_hanzi_1;
    QPushButton *pushButton_y;
    QPushButton *pushButton_hanzi_8;
    QPushButton *pushButton_splash;
    QPushButton *pushButton_f;
    QPushButton *pushButton_hanzi_4;
    QPushButton *pushButton_gang;
    QPushButton *pushButton_enter;
    QPushButton *pushButton_n6;
    QPushButton *pushButton_whitespace;
    QPushButton *pushButton_n5;
    QPushButton *pushButton_t;
    QPushButton *pushButton_hanzi_7;
    QPushButton *pushButton_i;
    QPushButton *pushButton_u;
    QPushButton *pushButton_hanzi_2;
    QPushButton *pushButton_o;
    QPushButton *pushButton_backsplash;
    QPushButton *pushButton_n4;
    QPushButton *pushButton_z;
    QPushButton *pushButton_c;
    QPushButton *pushButton_j;
    QPushButton *pushButton_q;
    QPushButton *pushButton_deng;
    QPushButton *pushButton_ok;
    QPushButton *pushButton_right;
    QPushButton *pushButton_semicolon;
    QPushButton *pushButton_hanzi_left;
    QPushButton *pushButton_n1;
    QPushButton *pushButton_r;
    QPushButton *pushButton_s;
    QPushButton *pushButton_p;
    QPushButton *pushButton_e;
    QPushButton *pushButton_comma;
    QPushButton *pushButton_n3;
    QPushButton *pushButton_b;
    QPushButton *pushButton_l;
    QPushButton *pushButton_w;
    QPushButton *pushButton_n7;
    QPushButton *pushButton_n2;
    QPushButton *pushButton_x;
    QPushButton *pushButton_m;
    QPushButton *pushButton_left;
    QPushButton *pushButton_down;
    QPushButton *pushButton_shift;
    QPushButton *pushButton_youkuo;
    QPushButton *pushButton_backspace;
    QPushButton *pushButton_n9;
    QPushButton *pushButton_hanzi_3;
    QPushButton *pushButton_h;
    QPushButton *pushButton_quote;
    QPushButton *pushButton_zuokuo;
    QPushButton *pushButton_hanzi_5;
    QPushButton *pushButton_n;
    QPushButton *pushButton_v;
    QPushButton *pushButton_period;
    QPushButton *pushButton_a;
    QPushButton *pushButton_hanzi_6;
    QPushButton *pushButton_g;
    QGroupBox *groupBox;
    QHBoxLayout *horizontalLayout_2;
    QLineEdit *lineEdit_window;
    QLineEdit *lineEdit_pinyin;
    QPushButton *pushButton_Cancel;

    void setupUi(QDialog *Dialog)
    {
        if (Dialog->objectName().isEmpty())
            Dialog->setObjectName(QStringLiteral("Dialog"));
        Dialog->setWindowModality(Qt::WindowModal);
        Dialog->resize(789, 419);
        QFont font;
        font.setPointSize(20);
        Dialog->setFont(font);
        Dialog->setSizeGripEnabled(false);
        Dialog->setModal(true);
        horizontalLayout = new QHBoxLayout(Dialog);
        horizontalLayout->setContentsMargins(0, 0, 0, 0);
        horizontalLayout->setObjectName(QStringLiteral("horizontalLayout"));
        frame = new QFrame(Dialog);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setFrameShape(QFrame::Box);
        frame->setFrameShadow(QFrame::Raised);
        frame->setLineWidth(2);
        pushButton_n0 = new QPushButton(frame);
        pushButton_n0->setObjectName(QStringLiteral("pushButton_n0"));
        pushButton_n0->setGeometry(QRect(465, 104, 45, 45));
        QFont font1;
        font1.setPointSize(20);
        font1.setBold(true);
        font1.setWeight(75);
        pushButton_n0->setFont(font1);
        pushButton_k = new QPushButton(frame);
        pushButton_k->setObjectName(QStringLiteral("pushButton_k"));
        pushButton_k->setGeometry(QRect(364, 218, 45, 45));
        pushButton_k->setFont(font1);
        pushButton_hanzi_right = new QPushButton(frame);
        pushButton_hanzi_right->setObjectName(QStringLiteral("pushButton_hanzi_right"));
        pushButton_hanzi_right->setGeometry(QRect(490, 60, 70, 35));
        pushButton_hanzi_right->setFont(font1);
        pushButton_n8 = new QPushButton(frame);
        pushButton_n8->setObjectName(QStringLiteral("pushButton_n8"));
        pushButton_n8->setGeometry(QRect(364, 104, 45, 45));
        pushButton_n8->setFont(font1);
        pushButton_is_hanzi = new QPushButton(frame);
        pushButton_is_hanzi->setObjectName(QStringLiteral("pushButton_is_hanzi"));
        pushButton_is_hanzi->setGeometry(QRect(331, 340, 61, 45));
        QFont font2;
        font2.setPointSize(15);
        font2.setBold(true);
        font2.setWeight(75);
        pushButton_is_hanzi->setFont(font2);
        pushButton_d = new QPushButton(frame);
        pushButton_d->setObjectName(QStringLiteral("pushButton_d"));
        pushButton_d->setGeometry(QRect(112, 218, 45, 45));
        pushButton_d->setFont(font1);
        pushButton_up = new QPushButton(frame);
        pushButton_up->setObjectName(QStringLiteral("pushButton_up"));
        pushButton_up->setGeometry(QRect(514, 278, 60, 45));
        pushButton_up->setFont(font1);
        pushButton_hanzi_1 = new QPushButton(frame);
        pushButton_hanzi_1->setObjectName(QStringLiteral("pushButton_hanzi_1"));
        pushButton_hanzi_1->setGeometry(QRect(90, 60, 45, 35));
        pushButton_hanzi_1->setFont(font2);
        pushButton_y = new QPushButton(frame);
        pushButton_y->setObjectName(QStringLiteral("pushButton_y"));
        pushButton_y->setGeometry(QRect(263, 160, 45, 45));
        pushButton_y->setFont(font1);
        pushButton_hanzi_8 = new QPushButton(frame);
        pushButton_hanzi_8->setObjectName(QStringLiteral("pushButton_hanzi_8"));
        pushButton_hanzi_8->setGeometry(QRect(442, 60, 45, 35));
        pushButton_hanzi_8->setFont(font2);
        pushButton_splash = new QPushButton(frame);
        pushButton_splash->setObjectName(QStringLiteral("pushButton_splash"));
        pushButton_splash->setGeometry(QRect(465, 278, 45, 45));
        pushButton_splash->setFont(font1);
        pushButton_f = new QPushButton(frame);
        pushButton_f->setObjectName(QStringLiteral("pushButton_f"));
        pushButton_f->setGeometry(QRect(163, 218, 45, 45));
        pushButton_f->setFont(font1);
        pushButton_hanzi_4 = new QPushButton(frame);
        pushButton_hanzi_4->setObjectName(QStringLiteral("pushButton_hanzi_4"));
        pushButton_hanzi_4->setGeometry(QRect(241, 60, 45, 35));
        pushButton_hanzi_4->setFont(font2);
        pushButton_gang = new QPushButton(frame);
        pushButton_gang->setObjectName(QStringLiteral("pushButton_gang"));
        pushButton_gang->setGeometry(QRect(515, 104, 45, 45));
        pushButton_gang->setFont(font1);
        pushButton_enter = new QPushButton(frame);
        pushButton_enter->setObjectName(QStringLiteral("pushButton_enter"));
        pushButton_enter->setGeometry(QRect(564, 218, 100, 45));
        pushButton_enter->setFont(font1);
        pushButton_n6 = new QPushButton(frame);
        pushButton_n6->setObjectName(QStringLiteral("pushButton_n6"));
        pushButton_n6->setGeometry(QRect(263, 104, 45, 45));
        pushButton_n6->setFont(font1);
        pushButton_whitespace = new QPushButton(frame);
        pushButton_whitespace->setObjectName(QStringLiteral("pushButton_whitespace"));
        pushButton_whitespace->setGeometry(QRect(115, 339, 210, 45));
        pushButton_whitespace->setFont(font1);
        pushButton_n5 = new QPushButton(frame);
        pushButton_n5->setObjectName(QStringLiteral("pushButton_n5"));
        pushButton_n5->setGeometry(QRect(213, 104, 45, 45));
        pushButton_n5->setFont(font1);
        pushButton_t = new QPushButton(frame);
        pushButton_t->setObjectName(QStringLiteral("pushButton_t"));
        pushButton_t->setGeometry(QRect(213, 160, 45, 45));
        pushButton_t->setFont(font1);
        pushButton_hanzi_7 = new QPushButton(frame);
        pushButton_hanzi_7->setObjectName(QStringLiteral("pushButton_hanzi_7"));
        pushButton_hanzi_7->setGeometry(QRect(392, 60, 45, 35));
        pushButton_hanzi_7->setFont(font2);
        pushButton_i = new QPushButton(frame);
        pushButton_i->setObjectName(QStringLiteral("pushButton_i"));
        pushButton_i->setGeometry(QRect(364, 160, 45, 45));
        pushButton_i->setFont(font1);
        pushButton_u = new QPushButton(frame);
        pushButton_u->setObjectName(QStringLiteral("pushButton_u"));
        pushButton_u->setGeometry(QRect(314, 160, 45, 45));
        pushButton_u->setFont(font1);
        pushButton_hanzi_2 = new QPushButton(frame);
        pushButton_hanzi_2->setObjectName(QStringLiteral("pushButton_hanzi_2"));
        pushButton_hanzi_2->setGeometry(QRect(140, 60, 45, 35));
        pushButton_hanzi_2->setFont(font2);
        pushButton_o = new QPushButton(frame);
        pushButton_o->setObjectName(QStringLiteral("pushButton_o"));
        pushButton_o->setGeometry(QRect(415, 160, 45, 45));
        pushButton_o->setFont(font1);
        pushButton_backsplash = new QPushButton(frame);
        pushButton_backsplash->setObjectName(QStringLiteral("pushButton_backsplash"));
        pushButton_backsplash->setGeometry(QRect(620, 160, 45, 45));
        pushButton_backsplash->setFont(font1);
        pushButton_n4 = new QPushButton(frame);
        pushButton_n4->setObjectName(QStringLiteral("pushButton_n4"));
        pushButton_n4->setGeometry(QRect(163, 104, 45, 45));
        pushButton_n4->setFont(font1);
        pushButton_z = new QPushButton(frame);
        pushButton_z->setObjectName(QStringLiteral("pushButton_z"));
        pushButton_z->setGeometry(QRect(11, 278, 45, 45));
        pushButton_z->setFont(font1);
        pushButton_c = new QPushButton(frame);
        pushButton_c->setObjectName(QStringLiteral("pushButton_c"));
        pushButton_c->setGeometry(QRect(112, 278, 45, 45));
        pushButton_c->setFont(font1);
        pushButton_j = new QPushButton(frame);
        pushButton_j->setObjectName(QStringLiteral("pushButton_j"));
        pushButton_j->setGeometry(QRect(314, 218, 45, 45));
        pushButton_j->setFont(font1);
        pushButton_q = new QPushButton(frame);
        pushButton_q->setObjectName(QStringLiteral("pushButton_q"));
        pushButton_q->setGeometry(QRect(11, 160, 45, 45));
        pushButton_q->setFont(font1);
        pushButton_deng = new QPushButton(frame);
        pushButton_deng->setObjectName(QStringLiteral("pushButton_deng"));
        pushButton_deng->setGeometry(QRect(566, 104, 45, 45));
        pushButton_deng->setFont(font1);
        pushButton_ok = new QPushButton(frame);
        pushButton_ok->setObjectName(QStringLiteral("pushButton_ok"));
        pushButton_ok->setGeometry(QRect(550, 340, 100, 45));
        QPalette palette;
        QBrush brush(QColor(0, 255, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QBrush brush1(QColor(118, 116, 108, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_ok->setPalette(palette);
        pushButton_right = new QPushButton(frame);
        pushButton_right->setObjectName(QStringLiteral("pushButton_right"));
        pushButton_right->setGeometry(QRect(480, 340, 60, 45));
        pushButton_right->setFont(font1);
        pushButton_semicolon = new QPushButton(frame);
        pushButton_semicolon->setObjectName(QStringLiteral("pushButton_semicolon"));
        pushButton_semicolon->setGeometry(QRect(465, 218, 45, 45));
        pushButton_semicolon->setFont(font1);
        pushButton_hanzi_left = new QPushButton(frame);
        pushButton_hanzi_left->setObjectName(QStringLiteral("pushButton_hanzi_left"));
        pushButton_hanzi_left->setGeometry(QRect(17, 60, 70, 35));
        pushButton_hanzi_left->setFont(font1);
        pushButton_n1 = new QPushButton(frame);
        pushButton_n1->setObjectName(QStringLiteral("pushButton_n1"));
        pushButton_n1->setGeometry(QRect(11, 104, 45, 45));
        pushButton_n1->setFont(font1);
        pushButton_n1->setFocusPolicy(Qt::ClickFocus);
        pushButton_r = new QPushButton(frame);
        pushButton_r->setObjectName(QStringLiteral("pushButton_r"));
        pushButton_r->setGeometry(QRect(163, 160, 45, 45));
        pushButton_r->setFont(font1);
        pushButton_s = new QPushButton(frame);
        pushButton_s->setObjectName(QStringLiteral("pushButton_s"));
        pushButton_s->setGeometry(QRect(62, 218, 45, 45));
        pushButton_s->setFont(font1);
        pushButton_p = new QPushButton(frame);
        pushButton_p->setObjectName(QStringLiteral("pushButton_p"));
        pushButton_p->setGeometry(QRect(465, 160, 45, 45));
        pushButton_p->setFont(font1);
        pushButton_e = new QPushButton(frame);
        pushButton_e->setObjectName(QStringLiteral("pushButton_e"));
        pushButton_e->setGeometry(QRect(112, 160, 45, 45));
        pushButton_e->setFont(font1);
        pushButton_comma = new QPushButton(frame);
        pushButton_comma->setObjectName(QStringLiteral("pushButton_comma"));
        pushButton_comma->setGeometry(QRect(364, 278, 45, 45));
        pushButton_comma->setFont(font1);
        pushButton_n3 = new QPushButton(frame);
        pushButton_n3->setObjectName(QStringLiteral("pushButton_n3"));
        pushButton_n3->setGeometry(QRect(112, 104, 45, 45));
        pushButton_n3->setFont(font1);
        pushButton_b = new QPushButton(frame);
        pushButton_b->setObjectName(QStringLiteral("pushButton_b"));
        pushButton_b->setGeometry(QRect(213, 278, 45, 45));
        pushButton_b->setFont(font1);
        pushButton_l = new QPushButton(frame);
        pushButton_l->setObjectName(QStringLiteral("pushButton_l"));
        pushButton_l->setGeometry(QRect(415, 218, 45, 45));
        pushButton_l->setFont(font1);
        pushButton_w = new QPushButton(frame);
        pushButton_w->setObjectName(QStringLiteral("pushButton_w"));
        pushButton_w->setGeometry(QRect(62, 160, 45, 45));
        pushButton_w->setFont(font1);
        pushButton_n7 = new QPushButton(frame);
        pushButton_n7->setObjectName(QStringLiteral("pushButton_n7"));
        pushButton_n7->setGeometry(QRect(314, 104, 45, 45));
        pushButton_n7->setFont(font1);
        pushButton_n2 = new QPushButton(frame);
        pushButton_n2->setObjectName(QStringLiteral("pushButton_n2"));
        pushButton_n2->setGeometry(QRect(62, 104, 45, 45));
        pushButton_n2->setFont(font1);
        pushButton_n2->setFocusPolicy(Qt::ClickFocus);
        pushButton_x = new QPushButton(frame);
        pushButton_x->setObjectName(QStringLiteral("pushButton_x"));
        pushButton_x->setGeometry(QRect(62, 278, 45, 45));
        pushButton_x->setFont(font1);
        pushButton_m = new QPushButton(frame);
        pushButton_m->setObjectName(QStringLiteral("pushButton_m"));
        pushButton_m->setGeometry(QRect(314, 278, 45, 45));
        pushButton_m->setFont(font1);
        pushButton_left = new QPushButton(frame);
        pushButton_left->setObjectName(QStringLiteral("pushButton_left"));
        pushButton_left->setGeometry(QRect(410, 340, 60, 45));
        pushButton_left->setFont(font1);
        pushButton_down = new QPushButton(frame);
        pushButton_down->setObjectName(QStringLiteral("pushButton_down"));
        pushButton_down->setGeometry(QRect(584, 278, 60, 45));
        pushButton_down->setFont(font1);
        pushButton_shift = new QPushButton(frame);
        pushButton_shift->setObjectName(QStringLiteral("pushButton_shift"));
        pushButton_shift->setGeometry(QRect(8, 339, 100, 45));
        pushButton_shift->setFont(font1);
        pushButton_youkuo = new QPushButton(frame);
        pushButton_youkuo->setObjectName(QStringLiteral("pushButton_youkuo"));
        pushButton_youkuo->setGeometry(QRect(566, 160, 45, 45));
        pushButton_youkuo->setFont(font1);
        pushButton_backspace = new QPushButton(frame);
        pushButton_backspace->setObjectName(QStringLiteral("pushButton_backspace"));
        pushButton_backspace->setGeometry(QRect(615, 104, 51, 45));
        QFont font3;
        font3.setPointSize(10);
        font3.setBold(true);
        font3.setWeight(75);
        pushButton_backspace->setFont(font3);
        pushButton_n9 = new QPushButton(frame);
        pushButton_n9->setObjectName(QStringLiteral("pushButton_n9"));
        pushButton_n9->setGeometry(QRect(415, 104, 45, 45));
        pushButton_n9->setFont(font1);
        pushButton_hanzi_3 = new QPushButton(frame);
        pushButton_hanzi_3->setObjectName(QStringLiteral("pushButton_hanzi_3"));
        pushButton_hanzi_3->setGeometry(QRect(190, 60, 45, 35));
        pushButton_hanzi_3->setFont(font2);
        pushButton_h = new QPushButton(frame);
        pushButton_h->setObjectName(QStringLiteral("pushButton_h"));
        pushButton_h->setGeometry(QRect(263, 218, 45, 45));
        pushButton_h->setFont(font1);
        pushButton_quote = new QPushButton(frame);
        pushButton_quote->setObjectName(QStringLiteral("pushButton_quote"));
        pushButton_quote->setGeometry(QRect(515, 218, 45, 45));
        pushButton_quote->setFont(font1);
        pushButton_zuokuo = new QPushButton(frame);
        pushButton_zuokuo->setObjectName(QStringLiteral("pushButton_zuokuo"));
        pushButton_zuokuo->setGeometry(QRect(515, 160, 45, 45));
        pushButton_zuokuo->setFont(font1);
        pushButton_hanzi_5 = new QPushButton(frame);
        pushButton_hanzi_5->setObjectName(QStringLiteral("pushButton_hanzi_5"));
        pushButton_hanzi_5->setGeometry(QRect(291, 60, 45, 35));
        pushButton_hanzi_5->setFont(font2);
        pushButton_n = new QPushButton(frame);
        pushButton_n->setObjectName(QStringLiteral("pushButton_n"));
        pushButton_n->setGeometry(QRect(263, 278, 45, 45));
        pushButton_n->setFont(font1);
        pushButton_v = new QPushButton(frame);
        pushButton_v->setObjectName(QStringLiteral("pushButton_v"));
        pushButton_v->setGeometry(QRect(163, 278, 45, 45));
        pushButton_v->setFont(font1);
        pushButton_period = new QPushButton(frame);
        pushButton_period->setObjectName(QStringLiteral("pushButton_period"));
        pushButton_period->setGeometry(QRect(415, 278, 45, 45));
        pushButton_period->setFont(font1);
        pushButton_a = new QPushButton(frame);
        pushButton_a->setObjectName(QStringLiteral("pushButton_a"));
        pushButton_a->setGeometry(QRect(11, 218, 45, 45));
        pushButton_hanzi_6 = new QPushButton(frame);
        pushButton_hanzi_6->setObjectName(QStringLiteral("pushButton_hanzi_6"));
        pushButton_hanzi_6->setGeometry(QRect(341, 60, 45, 35));
        pushButton_hanzi_6->setFont(font2);
        pushButton_g = new QPushButton(frame);
        pushButton_g->setObjectName(QStringLiteral("pushButton_g"));
        pushButton_g->setGeometry(QRect(213, 218, 45, 45));
        pushButton_g->setFont(font1);
        groupBox = new QGroupBox(frame);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(10, 10, 764, 41));
        horizontalLayout_2 = new QHBoxLayout(groupBox);
        horizontalLayout_2->setContentsMargins(0, 0, 0, 0);
        horizontalLayout_2->setObjectName(QStringLiteral("horizontalLayout_2"));
        lineEdit_window = new QLineEdit(groupBox);
        lineEdit_window->setObjectName(QStringLiteral("lineEdit_window"));
        QSizePolicy sizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(lineEdit_window->sizePolicy().hasHeightForWidth());
        lineEdit_window->setSizePolicy(sizePolicy);
        QFont font4;
        font4.setPointSize(21);
        font4.setBold(true);
        font4.setWeight(75);
        lineEdit_window->setFont(font4);
        lineEdit_window->setFrame(false);
        lineEdit_window->setCursorPosition(0);

        horizontalLayout_2->addWidget(lineEdit_window);

        lineEdit_pinyin = new QLineEdit(groupBox);
        lineEdit_pinyin->setObjectName(QStringLiteral("lineEdit_pinyin"));
        QSizePolicy sizePolicy1(QSizePolicy::Fixed, QSizePolicy::Expanding);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(lineEdit_pinyin->sizePolicy().hasHeightForWidth());
        lineEdit_pinyin->setSizePolicy(sizePolicy1);
        lineEdit_pinyin->setMaximumSize(QSize(150, 16777215));
        QFont font5;
        font5.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font5.setPointSize(21);
        font5.setBold(true);
        font5.setWeight(75);
        lineEdit_pinyin->setFont(font5);
        lineEdit_pinyin->setFocusPolicy(Qt::StrongFocus);
        lineEdit_pinyin->setFrame(false);

        horizontalLayout_2->addWidget(lineEdit_pinyin);

        pushButton_Cancel = new QPushButton(frame);
        pushButton_Cancel->setObjectName(QStringLiteral("pushButton_Cancel"));
        pushButton_Cancel->setGeometry(QRect(670, 340, 100, 45));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_Cancel->setPalette(palette1);

        horizontalLayout->addWidget(frame);


        retranslateUi(Dialog);

        QMetaObject::connectSlotsByName(Dialog);
    } // setupUi

    void retranslateUi(QDialog *Dialog)
    {
        Dialog->setWindowTitle(QApplication::translate("Dialog", "Dialog", 0));
        pushButton_n0->setText(QApplication::translate("Dialog", "0", 0));
        pushButton_k->setText(QApplication::translate("Dialog", "k", 0));
        pushButton_hanzi_right->setText(QApplication::translate("Dialog", "\342\206\222", 0));
        pushButton_n8->setText(QApplication::translate("Dialog", "8", 0));
        pushButton_is_hanzi->setText(QApplication::translate("Dialog", "Abc", 0));
        pushButton_d->setText(QApplication::translate("Dialog", "d", 0));
        pushButton_up->setText(QApplication::translate("Dialog", "\342\206\221", 0));
        pushButton_hanzi_1->setText(QString());
        pushButton_y->setText(QApplication::translate("Dialog", "y", 0));
        pushButton_hanzi_8->setText(QString());
        pushButton_splash->setText(QApplication::translate("Dialog", "/", 0));
        pushButton_f->setText(QApplication::translate("Dialog", "f", 0));
        pushButton_hanzi_4->setText(QString());
        pushButton_gang->setText(QApplication::translate("Dialog", "-", 0));
        pushButton_enter->setText(QApplication::translate("Dialog", "Enter", 0));
        pushButton_n6->setText(QApplication::translate("Dialog", "6", 0));
        pushButton_whitespace->setText(QApplication::translate("Dialog", "whitespace", 0));
        pushButton_n5->setText(QApplication::translate("Dialog", "5", 0));
        pushButton_t->setText(QApplication::translate("Dialog", "t", 0));
        pushButton_hanzi_7->setText(QString());
        pushButton_i->setText(QApplication::translate("Dialog", "i", 0));
        pushButton_u->setText(QApplication::translate("Dialog", "u", 0));
        pushButton_hanzi_2->setText(QString());
        pushButton_o->setText(QApplication::translate("Dialog", "o", 0));
        pushButton_backsplash->setText(QApplication::translate("Dialog", "\\", 0));
        pushButton_n4->setText(QApplication::translate("Dialog", "4", 0));
        pushButton_z->setText(QApplication::translate("Dialog", "z", 0));
        pushButton_c->setText(QApplication::translate("Dialog", "c", 0));
        pushButton_j->setText(QApplication::translate("Dialog", "j", 0));
        pushButton_q->setText(QApplication::translate("Dialog", "q", 0));
        pushButton_deng->setText(QApplication::translate("Dialog", "=", 0));
        pushButton_ok->setText(QApplication::translate("Dialog", "\347\241\256\345\256\232", 0));
        pushButton_right->setText(QApplication::translate("Dialog", "\342\206\222", 0));
        pushButton_semicolon->setText(QApplication::translate("Dialog", ";", 0));
        pushButton_hanzi_left->setText(QApplication::translate("Dialog", "\342\206\220", 0));
        pushButton_n1->setText(QApplication::translate("Dialog", "1", 0));
        pushButton_r->setText(QApplication::translate("Dialog", "r", 0));
        pushButton_s->setText(QApplication::translate("Dialog", "s", 0));
        pushButton_p->setText(QApplication::translate("Dialog", "p", 0));
        pushButton_e->setText(QApplication::translate("Dialog", "e", 0));
        pushButton_comma->setText(QApplication::translate("Dialog", ",", 0));
        pushButton_n3->setText(QApplication::translate("Dialog", "3", 0));
        pushButton_b->setText(QApplication::translate("Dialog", "b", 0));
        pushButton_l->setText(QApplication::translate("Dialog", "l", 0));
        pushButton_w->setText(QApplication::translate("Dialog", "w", 0));
        pushButton_n7->setText(QApplication::translate("Dialog", "7", 0));
        pushButton_n2->setText(QApplication::translate("Dialog", "2", 0));
        pushButton_x->setText(QApplication::translate("Dialog", "x", 0));
        pushButton_m->setText(QApplication::translate("Dialog", "m", 0));
        pushButton_left->setText(QApplication::translate("Dialog", "\342\206\220", 0));
        pushButton_down->setText(QApplication::translate("Dialog", "\342\206\223", 0));
        pushButton_shift->setText(QApplication::translate("Dialog", "shift", 0));
        pushButton_youkuo->setText(QApplication::translate("Dialog", "]", 0));
        pushButton_backspace->setText(QApplication::translate("Dialog", "Del", 0));
        pushButton_n9->setText(QApplication::translate("Dialog", "9", 0));
        pushButton_hanzi_3->setText(QString());
        pushButton_h->setText(QApplication::translate("Dialog", "h", 0));
        pushButton_quote->setText(QApplication::translate("Dialog", "'", 0));
        pushButton_zuokuo->setText(QApplication::translate("Dialog", "[", 0));
        pushButton_hanzi_5->setText(QString());
        pushButton_n->setText(QApplication::translate("Dialog", "n", 0));
        pushButton_v->setText(QApplication::translate("Dialog", "v", 0));
        pushButton_period->setText(QApplication::translate("Dialog", ".", 0));
        pushButton_a->setText(QApplication::translate("Dialog", "a", 0));
        pushButton_hanzi_6->setText(QString());
        pushButton_g->setText(QApplication::translate("Dialog", "g", 0));
        groupBox->setTitle(QString());
        lineEdit_window->setInputMask(QString());
        lineEdit_window->setText(QString());
        lineEdit_pinyin->setText(QString());
        pushButton_Cancel->setText(QApplication::translate("Dialog", "\345\217\226\346\266\210", 0));
    } // retranslateUi

};

namespace Ui {
    class Dialog: public Ui_Dialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SYSZUXPINYIN_H
